#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Aug 16 16:32:24 CST 2026
maven-metadata-aliyunmaven.xml.error=
maven-metadata-spring.xml.error=
maven-metadata-spring.xml.lastUpdated=1786869144715
maven-metadata-aliyunmaven.xml.lastUpdated=1628605948952
