#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Jun 11 10:49:26 CST 2021
maven-metadata-aliyunmaven.xml.error=
maven-metadata-aliyunmaven.xml.lastUpdated=1623379766210
